### ISSUE TITLE
Page register: champs et informations user

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#10]
Yep

A) pour le champ "identifiant" même si ce sera sans doute évident pour la plus part des users peut-on remplacer "Prenom" par "pseudo"
 Champ adresse mail remplacer "prenom-nom@email.com" par "adressemail@email.com" par exemple

B) Pour le champ mot de passe, est-il possible de préciser quelque part avec une info bulle par exemple "i" ou "?" ce qui est attendu pour la composition du pass exemple 1 chiffre + 1 maj + un symbole".

C) Lorsque l'on fait une erreur sur les mots de passe, notamment si la confirmation du pass est différente que le mot de passe du premier champ, un bandeau s'ouvre pour stipuler qu'il y a " Erreur lors de la création du votre compte". Est-il possible de stipuler plutôt une information qui précise où est l'erreur? Exemple "Erreur, les mots de passe sont différents" ou bien mettre en surbrillance les champs comportant une erreur

D) La question "Devenir Helper?" est-il possible de mettre une info bulle "i" ou "?" qui permet en passant la souris de savoir ce que représente être un Helper "Vous souhaitez devenir un dépanneur?"

E) "S'inscrire avec Google" peut-on ajouter aussi avec "Facebook"?

**Comment by antoine-leguillou** [comment]
Tooltips ajoutés sur les labels
