### ISSUE TITLE
Page sign in

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#11]
Yep

A) de mon écran de 13" ici aussi la phrase "De retour parmi nous" est rogné le haut des lettres est rogner, je mets une photo
![Page sign in](https://user-images.githubusercontent.com/55765086/107970938-15784f00-6fb2-11eb-8edf-277e5642964a.PNG)

B) Correction sur le mot "parmis" il faut lever le "S" 

C) Est-il possible d'ajouter en plus de Google "Se connecter avec facebook"

**Comment by antoine-leguillou** [comment]
A voir pour facebook

**Comment by AlainMcfly** [comment]
Ça marche :)

**Comment by antoine-leguillou** [comment]
Pris en compte prochaine pull request
