### ISSUE TITLE
Page register: confirmation du choix du profil

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#12]
Yep

est-il possible au moment de cliquer sur le bouton "s'inscrire" d'avoir lorsque l'on appuie dessus, un pop up qui apparait stipulant "Vous êtes sur le point de créer un profil en tant qu'Helper pour proposer vos services de dépannage" accompagner de deux boutons "confirmer" et "annuler" afin d'être sûr d'éviter  les erreurs de créations de compte.

**Comment by antoine-leguillou** [comment]
pop up  attachée au changement du radio non vers oui et non pas à la soumission du formulaire . Visiblke dans la prochaine pull request
