### ISSUE TITLE
Bandeau création de compte

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#13]
Yep

est-il possible d'ajouter après la création de compte dans le bandeau qui stipule "compte créé avec succès" d'ajouter à la suite "Veuillez vous connecter"

**Comment by antoine-leguillou** [comment]
Pris en compte dans la prochaine pull request

**Comment by AlainMcfly** [comment]
Nickel merci ça fonctionne bien
