### ISSUE TITLE
Vue d'un user/ PS: Certaines modif de cette issue ne sont plus utiles étant donné qu'on ne switch plus

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#14]
Lorsqu'on se connecte en tant que demandeur nous avons accès à la vue d'un Helper il y a:
- les annonces ainsi que le filtre des recherches pour les annonces à lever
- Le bouton "Les posts" dans la barre de navigation à lever

Dans la liste déroulant de "Mon compte" est-il possible de remplacer "Activité" par " Mes activités"

- Est-il possible dans la barre de navigation d'écrire les intitulés des boutons "MON COMPTE " "DECONNEXION" etc, avec un majuscule au début et le reste en minuscule "Mon compte" , "Publier", "Déconnexion", etc. Afin également d'avoir les accents notamment dans la liste déroulante de "Mon compte" avec "Mes activités"

**Comment by antoine-leguillou** [comment]
A) Lorsqu'on se connecte en tant que demandeur nous avons accès à la vue d'un Helper il y a:

    les annonces ainsi que le filtre des recherches pour les annonces à lever
    Le bouton "Les posts" dans la barre de navigation à lever

B) Dans la liste déroulant de "Mon compte" est-il possible de remplacer "Activité" par " Mes activités"

    Est-il possible dans la barre de navigation d'écrire les intitulés des boutons "MON COMPTE " "DECONNEXION" etc, avec un majuscule au début et le reste en minuscule "Mon compte" , "Publier", "Déconnexion", etc. Afin également d'avoir les accents notamment dans la liste déroulante de "Mon compte" avec "Mes activités"


A) Pas compris. Merci d'expliciter
B) Ok modifications faîtes

**Comment by AlainMcfly** [comment]
Hello Antoine,

pour le point [A] j'ai créé le compte en tant que demandeur pas en tant qu'Helper, donc afin de trouver de l'aide. Et en tant que demandeur il y a l'interface de l'helper c'est à dire que le demandeur a accès aux annonces, et la fonction de recherche d'annonce avec le filtre, par plateforme etc alors que c’est quelque chose qui est simplement pour les helper voulant répondre à un dépannage.

Du coup il faut donc aussi lever le bouton "Les posts". Lever tout ce qui correspond aux acces d'un helper. Mais je crois que Sabri me disait que c'était en cours

**Comment by antoine-leguillou** [comment]
Ok je vois mais dans le schema UX il était précisé redirection vers les posts quel que soit le status de l'utilisateur connecté que souhaite tu mettre en place ?

**Comment by AlainMcfly** [comment]
Ah d'accord, Je viens d'appeler il vient de me dire qu'effectivement il t'avait dis ça et l'avait indiqué sur l'arborescence, je ne savais pas.
Donc après discussion et par rapport à ce que je lui ai dit, ça serait plutôt de rediriger le demandeur vers la page d'accueil et non la page des annonces (mais sans lui empêcher de pouvoir accéder à la page des annonces s'il a envie)
Et du coup ce que je te disais précedemment dans cette issue et/ou d'autres issues de lever les boutons "Posts" etc, lorsque le demandeur est connecté n'est plus nécessaire car on part du principe que le demandeur peut lui aussi voir les annonces. Si ça reste confus pour toi on en a discuté avec Sabri il pourra te dire de vive voix ou on peut se tel 😉

**Comment by AlainMcfly** [comment]
En gros toute cette partie que je t'ai écrite n'est pas à toucher finalement:
"Lorsqu'on se connecte en tant que demandeur nous avons accès à la vue d'un Helper il y a:

les annonces ainsi que le filtre des recherches pour les annonces à lever
Le bouton "Les posts" dans la barre de navigation à lever"

La seule modif et de diriger le demandeur lors de la connexion ou l inscription vers la page accueil juste ça :))

Thanks

**Comment by AlainMcfly** [comment]
Oui effectivement je viens d'appeler Sabri et il m'a expliqué qu'il t'avait dit ça et qu'il l'avait du coup mentionné sur l'arborescence.
Mais après discussion finalement lorsque le Demandeur se connecte ou s'inscrit faudrait le diriger vers l'accueil￼.

En gros toute cette partie que je te disais de modifier n'est plus à changer finalement:
Cette partie:
["Lorsqu'on se connecte en tant que demandeur nous avons accès à la vue d'un Helper il y a:

les annonces ainsi que le filtre des recherches pour les annonces à lever
Le bouton "Les posts" dans la barre de navigation à lever"]

Merci à toi :))

**Comment by antoine-leguillou** [comment]
Ok pas de soucis j'attends la page d'acceuil

**Comment by AlainMcfly** [comment]
^^

nous partons donc sur un compte unique pour tous les users, plus de distinction entre helper et demandeur et donc de compte dédié. De ce fait:
-tous les users lors de la connexion devront arriver sur l'accueil et avoir le même affichage d'interface sans distinction:
- Les boutons "Publier" et "Les annonces" doivent apparaître ainsi que la partie recherche doit apparaitre, pour tous les users.

Je reprends les issues où il était mentionné d'apporter des modif liées au distinction de profil entre Helper et Demandeur même si je me doute que tu le sais, sachant que l'on ne switch plus d'un profil à un autre, mais c'est pour ne pas oublier :)

Thanks
