### ISSUE TITLE
Côté demandeur page Profil "Informations générales"

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#15]
Yep

La question "Devenir Helper?" est-il possible d'apporter une précision en remplaçant par "Devenir également Helper"

Ici le switch d'un compte à l'autre est proposer sur la page profil sera-t-il possible que cela soit en page d'accueil comme nous l'avions évoqué de la même manière que le fait le site troc de l'île afin que cela soit clairement visible

Thanks :)

**Comment by antoine-leguillou** [comment]
libellé changé voir avec sabri pour la page d'acceuil
