### ISSUE TITLE
Côté demandeur page Profil "Informations personnelles" / Compétences à lever/ Ps: les compétences ne sont plus à lever car on part sur un compte unique :)

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#16]
^^

Pour les informations obligatoires est-il  possible d'ajouter un * sur les champs concernés, c'est à dire tous sauf la numéro de téléphone

- Le champs compétences est à lever du côté du demandeur ( je le stipule mais je sais que vous le savez c'est simplement pour pas oublier :) )
Thanks

**Comment by antoine-leguillou** [comment]
Condition mise sur le display de la section compétence dans le menu à gauche et le container au centre

**Comment by AlainMcfly** [comment]
^^
Donc ici du coup, ne faisant plus de distinction de profil, il ne faut plus tenir compte de ce que j'avais écrit de lever les compétences côté demandeur, mais de les laisser pour tout le monde quel que soit le profil dans le où il n 'y a plus de profil Helper ou Demandeur : )

Thanks

**Comment by AlainMcfly** [comment]
Je close il y a une issue pour que tous les users aient accès aux compétences via leur profil :)
