### ISSUE TITLE
Page "Activités" dans > "Mes annonces"> "Mes offres" > "Mes demandes" côté demandeur

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#17]
Yep ^^

Dans « mes annonces »￼

Ajouter une majuscule sur la check box "toutes" > "Toutes"
Dans "Mes offres"

-Ajouter une maj sur "toutes, envoyées, reçues, en cours, déclinées"

Dans "mes demandes"

-Ajouter une maj sur "toutes"

Sur la phrase "Pas de demandes..." lever le S à demandes

Thanks😃

**Comment by AlainMcfly** [comment]
Yep ^^

Dans « mes annonces »￼

- Ajouter une majuscule sur la check box "toutes" > "Toutes"

Dans "Mes offres"

-Ajouter une maj sur "toutes, envoyées, reçues, en cours, déclinées"

Dans "mes demandes"

-Ajouter une maj sur "toutes"

Sur la phrase "Pas de demandes..." lever le S à demandes

Thanks😃

**Comment by antoine-leguillou** [comment]
Corrigé sera pris en compte dans la prochaine pull request
