### ISSUE TITLE
Corbeille et edition sur annonce 

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#20]
Hello 

il y a donc la possibilité d'éditer ou supprimer son annonce lorsque l'on tombe par exemple dessus en scrollant. Mais actuellement ces possibilités d'édition ou suppression se trouvent sur toutes les annonces, il faudrait qu'elles le soient uniquement sur l'annonce de la personne qui l'a posté.

thanks ;)

**Comment by antoine-tech** [comment]
Essayer de pull develop pour voir les MAJ, possiblilitée active uniquement pour l'auteur du post

**Comment by AlainMcfly** [comment]
Yes il n'y a donc plus la corbeille et l edition sur toutes les annonces c'est ok thanks. 

J'ai voulu tester de publier une annonce afin de voir si l edition/suppression était visible sur mon annonce mais pour le moment je ne peux publier (je suppose que c'est normal). Je te joins une capture pour te montrer ce que ça fait après avoir rempli tous les champs pour cliquer sur "Publier" ;)

![Publier annonce](https://user-images.githubusercontent.com/55765086/108756642-1298d380-7549-11eb-87ad-0c60cc05da17.PNG)

**Comment by antoine-leguillou** [comment]
Google Geocoding API est nécessaire ainsi que Places et Maps API activé dans le compte google developper

**Comment by AlainMcfly** [comment]
Sabri m'a dit que tout était activé. J'ai fais un screen des erreurs que j'ai dans la console de mon navigateur. Les deux premières erreurs apparaissent dès le chargement de la page. Les deux suivantes dès que je sélectionne l'adresse dans les suggestions d'autocomplétion.

![Capture d’écran du 2021-02-26 19-29-25](https://user-images.githubusercontent.com/55765086/109344014-733c4f00-786e-11eb-92d7-8702d0c63ee1.png)

**Comment by sabri-said** [comment]
Je viens de checker de mon côté, j'ai aussi les mêmes erreurs. J'ai bien vérifié les API activées et c'est OK de ce coté, j'ai Maps JavaScript API, Places API, Geocoding API et Geolocation API.

**Comment by AlainMcfly** [comment]
Hello,
Je viens de reesayer ça fait pareil malgré les vérif;)

merci à toi:)
