### ISSUE TITLE
Affichage des annonces

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#21]
^^

est-il possible de réduire par exemple de moitié, la taille des annonces :)

thanks

**Comment by antoine-leguillou** [comment]
Fait sur la nouvelle branche "reducing_publication_card_size",  merci de confimer le test avant ouverture de pull request

**Comment by AlainMcfly** [comment]
Yes merci, je viens de vérifier je vois la modif mais je te joins la photo de ce que ça donne sur mon ordi. Les photos sont rétrécies uniquement en largeur. 
![card](https://user-images.githubusercontent.com/55765086/108371976-9a57a880-71fe-11eb-9c88-1e144838badb.PNG)

**Comment by antoine-leguillou** [comment]
Ecrase le cache voir ?

**Comment by AlainMcfly** [comment]
J’ai effacé et pour le moment ca fait pareil

**Comment by AlainMcfly** [comment]
Après test on voit que pour que ce soit bon il faut soit essayer de reduire le bandeau de filtre de recherche pour laisser plus de place  aux annonces sur la largeur (mais esthétiquement ca peut faire bof) ou soit faire disparaître le bandeau à  partir de cette taille d'écran (ma resolution moi cest 1368 pixels environ) et pouvoir à la place,le faire apparaître manuellement avec un bouton à cliquer. ;)

**Comment by AlainMcfly** [comment]
La taille est ok merci je close:)
