### ISSUE TITLE
Question sur le switch de compte Demandeur/Helper / Ps: N'est plus d'actualité suite à l'interface commune=Ne plus mettre la question :)

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#22]
^^

Lorsque l'on se trouve dans la partie "Profil" > "Informations générales" il y a à la fin des champs la question/checkbox [Devenir Helper?]. C'est pour pouvoir faire un switch d'un compte Demandeur à Dépanneur? Comme on l'évoquait?

Si oui, je pense que c'est très bien de l'avoir là aussi et peut-on ajouter une info bulle [?] qui lorsque que l'on passe dessus ou clic affiche côté Demandeur : " Vous pouvez également partager vos compétences" et côté Helper: "Vous pouvez également obtenir de l'aide de la communauté".

Thanks

**Comment by antoine-leguillou** [comment]
PR adding tooltip and cursor help on label devenir helper ? users#edit

**Comment by AlainMcfly** [comment]
^^

Ceci n'a plus lieu d'être étant donné l'interface commune à tous les users, il ne faut plus poser la question "Devenir Helper?"
Thanks :)
