### ISSUE TITLE
Filtre recherche 

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#23]
^^

côté Helper est-il possible d'ajouter une flèche vers le bas du champ de recherche pour montrer qu'il y a une liste déroulante pour choisir la plateforme de la même manière que le champ [chercher autour de moi]. Et sur la phrase "Veuillez choisir une plateforme". De mon ordi en 13" le mot "plateforme" n'est pas visible entièrement il y a seulement "platefor". Pouvoir adapter de sorte que cela soit entier.

Toujours sur ce bandeau gauche où il y a le filtre de recherche, après le champ [chercher autour de moi], est-ce qu'il y a quelque chose d'autres? Car de mon PC je ne vois pas la fin de la partie et on ne peut scroller vers  le bas ( je mets une photo pour comprendre). Dans le cas où il n'y a pas plus rien après ce champ, il faudrait voir le bas de la partie de la même manière que l'on voit la haut de la partie délimité.
Par message c'est compliqué d'expliquer ce détail, je peux apporter d'autres précisions si besoin :)

![Page annonce bandeau recherche](https://user-images.githubusercontent.com/55765086/108193532-d82cd200-7115-11eb-9f5d-1d5d312f14ea.PNG)

Thanks

**Comment by antoine-leguillou** [comment]
PR reviewing_responsive_search_filters_posts#index

**Comment by AlainMcfly** [comment]
^^

C'est ok pour le bouton "Filtrer ma recherche"

Juste il manque la flèche vers le bas du champ de recherche pour montrer qu'il y a une liste déroulante pour choisir la plateforme de la même manière que le champ [chercher autour de moi]. Et optionnellement si tu peux réadapter sur la phrase "Veuillez choisir une plateforme" de mon ordi le mot "plateforme" n'est pas visible entièrement il y a seulement "platefor" mais c'est pas important si c'est galère ne fais pas :)

thanks

**Comment by antoine-leguillou** [comment]
Ok maj sur la prochaine pull request

**Comment by AlainMcfly** [comment]
Nickel pour le mot "plateforme" on le voit entièrement maintenant, il manque juste la flèche qui montre une liste déroulante :)
