### ISSUE TITLE
Champ numero de téléphone  dans "info personnelles" côté dépanneur : cela concerne maintenant tous les users 

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#25]
^^

Ici ajouter un * sur les champs obligatoires que sont: nom, prénom, date de naissance, adresse, ville, code postale. Et ne pas mettre de * sur le champ numéro de téléphone qui n'est pas obligatoire :)

thanks

**Comment by antoine-leguillou** [comment]
je pense qu'oobliger l'utilisateur à fournir autant d'informations personnelles serait contre productif

**Comment by AlainMcfly** [comment]
Oui tu n'as pas tort.
Les seuls champs obligatoires car utiles au fonctionnement sont: date de naissance car nous obligeons la majorité pour utiliser les services donc mettre un * pour ce champ

Le champ Code postal pour la localisation donc pareil un * sur ce champ

Et le champ Prenom/pseudo pareil un *

T'en penses quoi? :)

**Comment by AlainMcfly** [comment]
Hello
donc ici il faudrait ajouter des astérisques sur tous les champs sauf sur le champ "Numéro de téléphone"
