### ISSUE TITLE
Page accueil après connexion et inscription

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#30]
^^

Il faudrait que les users arrivent sur l'accueil après connexion/Inscription car il n y a  plus de distinction Helper/Demandeur :)

Thanks guys

**Comment by antoine-leguillou** [comment]
Fait. Redirection après inscription sur la page de connexion et redirection après connexion sur l'acceuil

**Comment by AlainMcfly** [comment]
cool thanks
