### ISSUE TITLE
Ajout de flèche pour champ liste déroulante Page "Publier" et Correction 

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#34]
^^

est-il possible stp, de pouvoir ajouter sur les champs "Plateforme de l'appareil" et "Type de panne" une flèche vers le bas afin de savoir qu'il y a une liste déroulante 
et si ce n'est pas possible de le faire moi même, de pouvoir modifier "plateforme de l'appareil" par "Type d'appareil" stp

Thanks :)

**Comment by antoine-leguillou** [comment]
ok passera sur la prochaine pull reaquest avec la page d'acceuil

**Comment by AlainMcfly** [comment]
Hello Antoine,

les modif de se sont pas actualisées pour cette issue. T'avais pu les faire? :)
