### ISSUE TITLE
Affichage Description Profil

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#37]
Hello,

lorsque l'on va sur le profil d'un user (je l'ai fait après avoir cliqué sur une annonce), la description prend tout l'écran je te joins une captutre :)

![Profil user](https://user-images.githubusercontent.com/55765086/108858083-12054900-75ec-11eb-98f9-52e9f93ca21a.PNG)

**Comment by antoine-leguillou** [comment]
Erreur php que je n'ai pas, voir si sabri à l'erreure penser à mettre à jour la bdd

**Comment by sabri-said** [comment]
J'ai n'ai pas l'erreur de mon coté, je ferais un teamviewer pour voir ce que c'est.
