### ISSUE TITLE
Implémentation du système mailer pour confirmation de compte/mot de passe oublié et process

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#42]
Antoine je te mets ici les accès à mailjet:
Acces mailjet:
accountverification@tynkle.com
Pass : (MyhomE2580( 
Les parenthèses font parties du mot de passe

Afin de pouvoir mettre en place le système d'envoi des mails automatiques pour :

1) -La vérification suite à la création de compte l'user reçoit un mail de confirmation

Avec la phrase d'envoi suivante qui sera sous forme de lien:

A) "Bonjour

vous venez de créer un compte sur Tynkle, merci de cliquer sur ce lien afin de finaliser votre inscription

Salutations
L'équipe Tynkle "

B) Après avoir cliquer une page Tynkle s'ouvre avec le message "Votre compte a bien été validé vous pouvez vous connecter"

2) -Pour "Mot de passe oublié" l'user reçoit un mail avec avec la phrase d'envoi suivante qui sera sous forme de lien:

A) "Bonjour,

vous avez demandé à réinitialiser votre de mot passe, cliquez sur ce lien afin d'en créer un nouveau.
Si cette action ne vient pas de vous merci de supprimer ce mail et de modifier par sécurité votre mot de passe dans les paramètres de votre compte.

Salutations
L'équipe Tynkle"

B) Après avoir cliquer cela ouvre une page Tynkle avec:

-En titre "Réinitialisation de mot de passe"
- Un premier champ "Entrez un mot de passe"
- Un deuxième "Confirmez votre de mot de passe"
- Un bouton "Valider"

C) Suite à cela une page ou un bandeau ou popup affiche "Mot de passe remplacé avec succès, vous pouvez vous connecter"

L'issue 43 explique le process utilisateur pour le mot de passe oublié et l'issue 44 explique le process utilisateur pour la validation de l'adresse après création de compte.

Thanks :)

**Comment by antoine-leguillou** [comment]
Ok done

**Comment by AlainMcfly** [comment]
Merci :)
