### ISSUE TITLE
Process "Mot de passe oublié"

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#43]
Lorsqu'un user clique sur le lien "mot de passe oublié" se trouvant sous le champ "Mot de passe" de la page "Connexion":

1) Cela lui ouvre une page demandant dans un champ d'insérer l'adresse mail du compte : en titre "Mot de passe oublié" en dessous "Entrez l'adresse mail associée à votre compte"

2) L'user  rempli le champ

3) Après avoir rempli le champ avec l'adresse mail , l'user clique sur le bouton "Continuer" ce qui ouvre un popup ou une bandeau ou une page pour dire "Vous allez recevoir un mail de réinitialisation de mot de passe" et cela envoie le mail correspond qui se trouve dans l'issue 42 à l'adresse mail indiquée.

4) Si l'adresse  mail n'est pas répertorié dans la BDD un message d'erreur s'affiche "Votre adresse mail ne correspond à aucun compte existant, merci de recommencer"

Merci :)
je te joins une photo pour exemple:

![Pass oublié](https://user-images.githubusercontent.com/55765086/109505628-15da1500-7a9d-11eb-8f5d-c482aef7cfea.PNG)

**Comment by antoine-leguillou** [comment]
Ok PR à suivre

**Comment by AlainMcfly** [comment]
Top merci

**Comment by AlainMcfly** [comment]
Le process est ok mais les liens ne semble pas fonctionner lorsque l'on clique cela ne réagit pas.
