### ISSUE TITLE
Blog/SEO

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#47]
Hello,

lorsque ce sera possible, et je l'écrit aussi pour ne pas oublier. Pour le travail du SEO sera t i l possible  de mettre en place un blog pour la rédaction d'article ,avec  gestion via le back office?

La partie blog serait accessible pour l'user via un  bouton "Blog" depuis la page d'accueil, celle-ci ouvrira la page "Blog" sur laquelle il y a des articles:

- Une barre de navigation avec des catégories: Nouveautés |Tous les articles | Fonctionnement| Tynkle

- Chaque article pourra apparaitre à la manière de getaround pour exemple : https://community.fr.getaround.com/ 

Ainsi un aperçu de l'articule sera visible faisant apparaitre: photo, titre et première ligne de l'article avec un bouton "Lire la suite" qui ouvrira l'article dans une nouvelle page voir photo jointe ;)

(En soit au niveau de l'esthétique pas d'impératif)

![Blog](https://user-images.githubusercontent.com/55765086/109664791-d16a7a00-7b6d-11eb-87f0-9dad453e238d.png)

**Comment by antoine-leguillou** [comment]
Ok prochaine PR
