### ISSUE TITLE
Formulaire de contact

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#48]
Est-il possible de mettre en place le formulaire de contact (sera accessible sur le footer) sur système mailer.

Le bouton "Contact" accessible depuis le footer ouvrira une page contact comme cela se fait de façon classique avec:

- Intitulé de page "Nous sommes à votre écoute, une réponse rapide dans la mesure du possible, pensez à la FAQ"
- Un champ "Objet "
- une zone pour le message
- un bouton "envoyer"
- après l'envoi un message "Envoyé avec succès" ou "Erreur, recommencez" si un bug
- Et inscrire également l'adresse mail de contact dans le cas où il y a un souci technique "contact@tynkle.com"

Photo pour exemple en  pièce jointe ;)
![contat-form](https://user-images.githubusercontent.com/55765086/109671518-738d6080-7b74-11eb-9fa7-a8f3ffe61c9a.png)

Merci:)

**Comment by antoine-leguillou** [comment]
ok

**Comment by AlainMcfly** [comment]
Merci, j’ai bien reçu le test sur contact@tynkle.com
Ça fonctionne :)

 ![image](https://user-images.githubusercontent.com/55765086/110040267-cfa5df80-7d42-11eb-901a-fd05b1475e83.png)
