### ISSUE TITLE
Page d'accueil

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#50]
Hello Antoine,

je viens de voir la page d'accueil beau travail, ça se rapproche de se que Sabri m'a montré de ce qu'il a codé pour la page d'accueil lui aussi de son côté.
Tu as fait de bons choix pour les illustrations :) 

A) peux-tu stp au dessus de la barre de nav ajouter à gauche du bouton "Connexion" un bouton "J'ai besoin d'aide" comme celui de "connexion et inscription" qui renverra sur le formulaire de demande.

Et également ajouter un bouton "Devenir Helper" qui renvoie sur la section [Tu veux aider la communauté ?
Deviens Helper !] du bas du site en scrollant (même s'il n'y a plus d'interface type pour Helper ou demandeur, ça permet un raccourci pour ce qui veulent directement faire que ça) et un bouton "Toutes les annonces" ces deux boutons se trouveront eux à droite du logo Tynkle (je te mets une photo)
![Boutons](https://user-images.githubusercontent.com/55765086/109842585-807c8380-7c4a-11eb-9f9f-008862e00e62.PNG)

B) Du coup dans la continuité du fait d'avoir levé le switch de profil peux-tu stp: ajouter cette phrase dans la première section du site juste avant les boutons "Les annonces" (je te mets une photo):

"Au sein de la communauté vous pouvez obtenir de l'aide et/ou partager vos services, pour cela il suffit de remplir vos compétences"

Le mot "compétences" peut être souligner et à cliquer pour renvoyer sur la partie compétence dans le profil ou sur la section qui explique ce que peut faire le dépanneur sur le bas de la page d'accueil

![ça ou ça](https://user-images.githubusercontent.com/55765086/109842934-dbae7600-7c4a-11eb-8b84-76300251106a.PNG)

C) Peux-tu ajouter stp les mots "et électroménager" à la phrase de présentation de la plateforme:
 "Tynkle, LA première plateforme exclusivement dédiée à l'entraide informatique et multimédia" qui donnera "Tynkle, LA première plateforme exclusivement dédiée à l'entraide informatique, multimédia et électroménager" merci, je te mets une photo aussi (un [et] est a léver et remplacer par une virgule:
![Et électroménager](https://user-images.githubusercontent.com/55765086/109844146-254b9080-7c4c-11eb-9da6-e2aae9e42dd3.PNG)

D) Et ajouter cette phrase "Astuce, augmente ton taux de réponse en faisant les deux" je te mets aussi une photo :)

![Astuce](https://user-images.githubusercontent.com/55765086/109843154-0e586e80-7c4b-11eb-8442-aa70cc8d8396.PNG)

E) et pouvoir espacer un peu les encadrés des différents posts d'avis, délimiter les encadrés stp
où il y a "faites comme Ben" en scrollant vers le bas du site

Merci et encore bravo pour la page :)

**Comment by antoine-leguillou** [comment]
A) peux-tu stp au dessus de la barre de nav ajouter à gauche du bouton "Connexion" un bouton "J'ai besoin d'aide" comme celui de "connexion et inscription" qui renverra sur le formulaire de demande.

Salut pour acceder au formualire de publicatio  d'une annonce l'utilisateur connecté est obligatoire à voir avec Sabri si le multistep est terminé ?

**Comment by AlainMcfly** [comment]
Salut oui effectivement l user doit être connecté pour accéder au formulaire de demande, Sabri est dessus. 
A voir quand tu ajoutes le bouton "j'ai besoin d'aide" pour le relier au formulaire ;)

**Comment by AlainMcfly** [comment]
Hello Antoine,

je viens de voir que tu as fait nouvelle version de la page d'accueil. Celle que tu avais fait  était vraiment bien, y'avait juste les détails que je t'ai mis dans l'issue, mais sinon RAS vraiment elle était top. Cette nouvelle version est beaucoup plus dans le blanc. C'est possible de revenir sur l'autre? Je trouve qu'elle collait vraiment à l'esprit de Tynkle dans les choix que tu avais fait:)

Merci à toi

**Comment by AlainMcfly** [comment]
Màj Pas grave, si la nouvelle version reste, pas important, pas prioritaire.

merci:)
