### ISSUE TITLE
Page aide

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#53]
Hello,

je te mets un word/pdf avec le contenu de l'aide qui peut se présenter simplement sur une page accessible à partir d'un bouton "Aide" situé dans le footer. Cette page fera apparaître le contenu du documents:
[Page Aide.docx](https://github.com/antoine-leguillou/Tynkle/files/6084456/Page.Aide.docx)
[Page Aide.pdf](https://github.com/antoine-leguillou/Tynkle/files/6084457/Page.Aide.pdf)

 ou bien pourra ressembler à ce site:
https://assistance.leboncoin.info/hc/fr

Par rapport au word/pdf si l'on prend l'exemple du site LBC qui affiche les catégories avec des carrés contenant des logos, pour Tynkle ces carrés reprendront les catégories situées dans le word/pdf intitulées "Catégories".
Après avoir cliqué sur  un carré catégorie il y aurait les informations du word/pdf contenues dans chaque catégorie avec un affichage simple et les informations les unes à la suite des autres séparées par une puce par exemple comme sur le word/pdf.
Tu peux aussi agrémenter si tu as une idée que tu trouves plus sympa :)

Avec une barre de recherche par mots clés "Comment pouvons-nous vous aider ?" pour trouver une information rapidement

Merci:)

**Comment by antoine-leguillou** [comment]
Ok prochaine PR
