### ISSUE TITLE
Favoris

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#55]
^^

je sais plus si j'en avais parlé:
est-il possible de mettre en place la possibilité de mettre un user en favoris: en étant sur son profil avec un logo "coeur" proche de sa photo afin de pouvoir le retrouver rapidement. Et du coup avoir un accès avec un bouton "Favoris" sur la barre avec "Mon compte" etc?

Thanks:)

**Comment by antoine-leguillou** [comment]
ok prochaine PR

**Comment by AlainMcfly** [comment]
Hello,

merci, du coup avoir la possibilité de lever l'user des favoris si l'on ajoute. (soit en recliquant sur le logo, soit avec un bouton lever des favoris" (sur le trello on a écrit bouton "lever des favoris" je crois mais bon peu importa la manière.

Et un détail même si ça va de soit: le bouton favoris sur la page d'accueil ouvre une page contenant une liste des favoris avec un aperçu du profil montrant photo, pseudo, et peut-être quelques détails d'informations/compétences :)
Merci

**Comment by antoine-leguillou** [comment]
Pour le moment on accède aux favoris dans Mon activitée / Mes favoris 
 - Si tu ajoute quelqu'un via son profil publique tu peut accéder de nouveau à ce dernier par une carte utilisateur et le retirer des favoris.
 
![Capture d’écran du 2021-03-10 08-11-04](https://user-images.githubusercontent.com/62133905/110590714-7097fe80-8178-11eb-9612-d44f184b9842.png)

**Comment by AlainMcfly** [comment]
Ah bah c’est Nickel comme ça :)
Cool merci
