### ISSUE TITLE
Composition mot de passe

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#59]
Est-il possible de rendre le création du mot de passe plus complexe?
Si c'est chiant à faire ne t'embête pas :)

7 caractères dont au moins une majuscule et au moins un chiffre
Lorsque la combinaison n'est pas effectuée, stipuler ce qu'il manque

Merci:)

**Comment by antoine-leguillou** [comment]
Très pénible d'un point du point de vue utilisateur je ne conseille pas...

**Comment by AlainMcfly** [comment]
Ça marche :)
