### ISSUE TITLE
Bouton CGU/Mentions légales

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#61]
^^

Peux tu stp ajouter le bouton "CGU & Mentions légales" dans le footer stp qui ouvrira une page les contenant. 
Je finalise les CGU et je les ajoutes. Tu peux t occuper de ça quand je les  mets si tu veux, là je fais l issue pour ne pas oublier.

Merci

**Comment by antoine-leguillou** [comment]
ok prochaine PR
