### ISSUE TITLE
Note sur annonce

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#73]
^^ 

Quand on accède aux annonces en cliquant sur le bouton "les annonces" via la barre de nav il y a bien une note se faisant sur 5 mais, il y a 3 étoiles au lieu de 5. 

:)

**Comment by antoine-leguillou** [comment]
Je n'ai pas compris dsl screeshots ? :)

**Comment by AlainMcfly** [comment]
Salut
 voici le screeshots, ce n'est pas le cas sur toutes les annonces j'en ai regardé plusieurs dans différentes catégories, il y a par exemple l'annonce intitulée "super titre 2 et 14" dans la catégorie smartphone, ou 27 dans electro, ou 4 et 6 dans d'autres catégorie. Ou alors dans chaque catégorie où il y a ces mêmes annonces j'ai l'impression.

![Note](https://user-images.githubusercontent.com/55765086/111304453-0ab6e580-8656-11eb-9811-541f8147dff0.PNG)

**Comment by antoine-leguillou** [comment]
Ok

**Comment by antoine-leguillou** [comment]
Ok

**Comment by antoine-leguillou** [comment]
Ok
