### ISSUE TITLE
Fixer un call pour la suite :)

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#76]
Salut les gars est-ce qu'il serait possible de fixer un jour, une heure pour s'appeler? Je suis pas sûr de la façon de te joindre Antoine, peut-être que tu n'as plus le même num, dans le doute je passe par ici. ça serait pour faire un petit point rapide ensemble :)

Merci bon après M

**Comment by sabri-said** [comment]
Yes c'est ok pour moi.

**Comment by AlainMcfly** [comment]
Ok cool, juste 15 minutes d'échange pour la suite. Je m'adapte en fonction de vos dispo. Moi j’ai jeudi et vendredi après midi et ce weekend n importe quand.
On attend le retour d'Antoine 😉

Merci les gars
