### ISSUE TITLE
Titre sur pages des annonces

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#77]
Est-il possible stp de mettre sur la page des annonces le titre : "Les annonces" en haut au milieux?

Ceci dans le but que lorsqu'un utilisateur clique sur leur des boutons de la barre de navigation lors des premières fois, qu'il puisse comprendre qu'ici se trouve seulement les annonces et que  pour rechercher de l'aide cela se passe ailleurs. Car en voyant les différentes catégories sur la barre de nav il se peut qu'il ne sache pas directement que les boutons soient simplement pour arriver sur les annonces.

Merci :)

**Comment by antoine-leguillou** [comment]
Ok
