### ISSUE TITLE
Nouvelle page d'accueil

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#81]
Hello Antoine,

concernant la nouvelle page d'accueil tout semble là, merci. Serait-il d'apporter des modifications en terme de "design", on va rester sur cette page pour ne pas repartir de zéro mais simplement apporter des modif:
La barre de recherche est vraiment top :)
-Sur celle-ci tout est tiré vers le blanc, du coup cela manque de séparation entre les sections, est-il donc possible d'apporter plus de nuances entre les sections, un dégradé d'une section/partie à une autre dans les tons gris/blanc/gris clair et un peu plus foncé etc.

- Est-il possible d'avoir des boutons apparents pour les call to action, actuellement cela fait simplement la phrase avec une flèche

- Dans la partie "Réparer plutôt que jeter" est-il possible d'avoir les logo ajustés sur la même ligne ou  bien diviser en 2 x 2 logo histoire d'avoir une répartition  égale.  Et d'avoir des logo plus gros, actuellement les phrases sont plus marquées que les logos, si l'on peut les grossir cela compensera je pense. Pareil pour la partie "Tu veux aider la communauté ? Deviens Helper !" Et un designde logo plutôt comme la toute première page ou la deuxième page que tu avais proposé.

- Pour la partie "Tynkle, un moyen simple de trouver des spécialistes" est-il possible de reprendre l'idée de départ avec une photo à droite et du texte à gauche, actuellement cela fait trop de texte sans image. 

Voilà merci sinon tout est cool beau travail merci

**Comment by antoine-leguillou** [comment]
Ok
