### ISSUE TITLE
bug barre de recherche Nouvelle page d'accueil et ajoute flèche dans barre de recherche

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#82]
Hello,

un petit bug que j'ai constaté:
lorsque que tu effectues une recherche, il y a donc en première proposition à l'ouverture du site la catégorie "informatique" si ensuite on choisit le type de panne on remarque que cela propose toutes les pannes de toutes les catégories confondues. 
Afin de gommer cela, il faut d'abord mettre une catégorie différente exemple 'smartphone' puis revenir sur "informatique" et là on a les type de panne uniquement liées à l'informatique. :)

Et comme nous en avions discuter si tu peux ajouter les fléchettes vers le bas dans les champs de recherche afin de montrer qu'il y a une liste déroulante. Stp je crois que tu m'avais dit que c'était selon le navigateur mais que tu pouvais les ajouter.

Merci à toi

**Comment by antoine-leguillou** [comment]
Ok
