### ISSUE TITLE
Redimension Page register et Sign in

### ISSUE THREAD

**Issue by AlainMcfly** [antoine-leguillou/Tynkle#9]
Hello ;)

de mon PC qui est en 13" je constate que la page n'est pas adaptée, c'est à dire que la  phrase "Rejoindre Tynkle" a le haut de ses lettre rogné, même en étant au plus haut de la page.
PS: et de façon générale ces pages ne sont pas en pleine pages, pour voir "se connecter, s'inscrire et FAQ" il faut scroller vers le bas (mais ça c'est peut-être normal)
![Page sign in register](https://user-images.githubusercontent.com/55765086/107968110-3dfe4a00-6fae-11eb-8ba7-0bd02d7886b4.PNG)

**Comment by antoine-leguillou** [comment]
Pris en compte prochaine pull request

**Comment by AlainMcfly** [comment]
👌
